# Generated by Django 4.2.4 on 2023-08-20 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Treino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('A', 'Treino-A'), ('B', 'Treino-B'), ('C', 'Treino-C'), ('D', 'Treino-D'), ('E', 'Treino-E')], max_length=1)),
            ],
        ),
    ]
