# Generated by Django 4.2.4 on 2023-08-21 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lis_savio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='treino',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='img_treinos/'),
        ),
        migrations.AlterField(
            model_name='treino',
            name='categoria',
            field=models.CharField(choices=[('Treino(A)', 'Treino-A'), ('Treino(B)', 'Treino-B'), ('Treino(C)', 'Treino-C'), ('Treino(D)', 'Treino-D'), ('Treino(E)', 'Treino-E')], max_length=9),
        ),
    ]
